#!/bin/bash

. ~/.conf/settings

if [ ! -d $_conf_orig ]
then
    /bin/mkdir $_conf_orig
fi

for _file in "${_conf_files[@]}"
do
    if [ ! -h "~/.${_file}" ]
    then
        if [ -e "~/.${_file}" ]
        then
            /bin/cp -rp "~/.${_file}" "${_conf_orig}/${_file}"
        fi

        /bin/ln -s "${_conf}/${_file}" "~/.${_file}"
        echo "Successfully installed: ~/.${_file}"
    else
        echo "Previously installed: ~/.${_file}"
    fi
done

for _file in "${_ssh_files[@]}"
do
    if [ ! -h "~/.ssh/${_file}" ]
    then
        if [ -e "~/.ssh/${_file}" ]
        then
            /bin/cp -rp "~/.ssh/${_file}" "${_conf_orig}/ssh_${_file}"
        fi

        /bin/ln -s "${_conf}/ssh_${_file}" "~/.ssh/${_file}"
        echo "Successfully installed: ~/.ssh/${_file}"
    else
        echo "Previously installed: ~/.ssh/${_file}"
    fi
done
