#!/usr/bin/env bash

. $HOME/.conf/settings

if [ ! -d $_conf_orig ]
then
    /bin/mkdir $_conf_orig
fi

for _file in "${_conf_files[@]}"
do
    if [ ! -h "$HOME/.${_file}" ]
    then
        if [ -e "$HOME/.${_file}" ]
        then
            /bin/mv "$HOME/.${_file}" "${_conf_orig}/${_file}"
        fi

        /bin/ln -s "${_conf}/${_file}" "$HOME/.${_file}"
        echo "Successfully installed: ~/.${_file}"
    else
        echo "Previously installed: ~/.${_file}"
    fi
done

for _file in "${_ssh_files[@]}"
do
    if [ ! -h "$HOME/.ssh/${_file}" ]
    then
        if [ -e "$HOME/.ssh/${_file}" ]
        then
            /bin/mv "$HOME/.ssh/${_file}" "${_conf_orig}/ssh_${_file}"
        fi

        /bin/ln -s "${_conf}/ssh_${_file}" "$HOME/.ssh/${_file}"
        echo "Successfully installed: ~/.ssh/${_file}"
    else
        echo "Previously installed: ~/.ssh/${_file}"
    fi
done

. $HOME/.bashrc
