#!/usr/bin/env bash

_conf="$HOME/.conf/conf"
_conf_orig="$HOME/.conf_orig"
_conf_files=( \
    bashrc bash_profile profile bash_logout \
    gitconfig \
    screenrc \
    vim vimrc \
    dzil perlcriticrc perltidyrc proverc perldb replyrc \
    sqliterc
)
_ssh_files=( config all_keys )
