#!/usr/bin/env bash

_conf="$HOME/.conf/conf"
_conf_orig="$HOME/.conf_orig"
_conf_files=( \
    bashrc bash_profile profile bash_logout \
    gitconfig gitignore \
    screenrc \
    vim vimrc \
    dzil perlcriticrc perltidyrc proverc yath.rc perldb replyrc pause \
    sqliterc
)
_ssh_files=( config all_keys )
