#!/bin/bash

. $HOME/.conf/settings

for _file in "${_conf_files[@]}"
do
    if [[ -h "$HOME/.${_file}" && -e "${_conf_orig}/${_file}" ]]
    then
        /bin/rm "$HOME/.${_file}"
        /bin/mv "${_conf_orig}/${_file}" "$HOME/.${_file}"
        echo "Successfully uninstalled: ~/.${_file}"
    else
        echo "Not previously installed: ~/.${_file}"
    fi
done

for _file in "${_ssh_files[@]}"
do
    if [[ -h "$HOME/.ssh/${_file}" && -e "${_conf_orig}/ssh_${_file}" ]]
    then
        /bin/rm "$HOME/.ssh/${_file}"
        /bin/mv "${_conf_orig}/ssh_${_file}" "$HOME/.ssh/${_file}"
        echo "Successfully uninstalled: ~/.ssh/${_file}"
    else
        echo "Not previously installed: ~/.ssh/${_file}"
    fi
done

if [ -d $_conf_orig ]
then
    /bin/rmdir $_conf_orig
fi

. $HOME/.bashrc
