#!/usr/bin/env perl
use strict;
use warnings;
use LWP::UserAgent;
use JSON::XS 'decode_json';

my $ua = LWP::UserAgent->new;

sub get {
    my $res = $ua->get( $_[0] );
    die $res->status_line . "\n" unless $res->is_success;
    return $res;
}

sub json {
    return decode_json( $_[0]->decoded_content );
}

my $repos = get('https://api.github.com/users/gryphonshafer/repos');
my @pages = ($repos);
push( @pages, get( 'https://api.github.com/users/gryphonshafer/repos?page=' . $_ ) )
    for ( 2 .. ( ( $repos->header('Link') =~ /page=(\d+)/ ) ? $1 : 1 ) );

my $issues_count;
for my $page (@pages) {
    for my $repo ( grep { $_->{open_issues_count} } @{ json $page } ) {
        printf "%-48s %10d issues\n", $repo->{name}, $repo->{open_issues_count};

        for my $issue (
            grep { $_->{state} eq 'open' } @{
                json get( 'https://api.github.com/repos/gryphonshafer/' . $repo->{name} . '/issues' )
            }
        ) {
            $issues_count++;
            printf "%6d: %-60s %s\n",
                $issue->{number},
                $issue->{title},
                $issue->{html_url};
        }
    }
}

if ($issues_count) {
    printf "%59d issues\n", $issues_count;
}
else {
    printf "%d issues\n", $issues_count;
}
