#!/usr/bin/env bash

cd $HOME

perls=( $( perlbrew list | grep -v @ | sed 's/^\s*//' ) )

cpanms=(
    $(
        find $(
            \ls -a | grep -v backups | grep -v .cpanm | grep -v '^\.\.$' | grep -v '^\.$'
        ) -type f -name cpanfile | xargs dirname
    )
    $(
        find $(
            \ls -a | grep -v backups | grep -v .cpanm | grep -v '^\.\.$' | grep -v '^\.$'
        ) -type f -name Makefile.PL | xargs dirname
    )
)

tests=(
    $(
        find $(
            \ls -a | grep -v backups | grep -v .cpanm | grep -v '^\.\.$' | grep -v '^\.$'
        ) -type d -name t | xargs dirname
    )
)

perllib="example"

dirs=("${tests[@]}")

builtin source /opt/perl5/etc/bashrc
export PERL_CPANM_OPT="-M https://cpan.metacpan.org/ --verify"

for perl in "${perls[@]}"
do
    printf '=%.0s' {1..150}
    echo '>' $perl

    perlbrew lib create $perl@$perllib
    perlbrew use $perl@$perllib

    cpanm -n Module::Signature Digest::SHA

    for dir in "${dirs[@]}"
    do
        printf '=%.0s' {1..80}
        echo '>' $HOME/$dir

        cd $HOME/$dir

        cpanm -n --installdeps . --with-recommends --with-suggests --with-develop --with-configure --with-all-features
        rm -f MYMETA.json MYMETA.yml Makefile

        prove --norc -lr t
    done

    perlbrew lib delete $perl@$perllib
done
