#!/usr/bin/env bash

export PERL_CPANM_OPT="--force --notest --from https://cpan.metacpan.org --skip-satisfied"

alias cpanmid="cpanm --installdeps ."
alias cpanmida="cpanmid --with-recommends --with-suggests --with-develop --with-configure --with-all-features"
alias cpanmsig="cpanm Module::Signature Digest::SHA"
alias cpanzuse="cpanm exact exact::cli IO::Socket::SSL Module::CPANfile Mojolicious Perl::PrereqScanner"
alias cpanmx="cpanm --with-recommends --with-suggests --with-develop --with-configure --with-all-features --force --notest --skip-satisfied --from https://cpan.metacpan.org --installdeps ."

alias pc="cover -delete -silent; HARNESS_PERL_SWITCHES=-MDevel::Cover prove t; cover -silent"
alias pr=prove
alias prv="prove --norc -v"

alias yt="yath test"
alias ytc="cover -delete -silent; yath test --cover; cover -silent"
alias ytp="rm ./nytprof.out.*; yath test --nytprof; nytprofhtml -d -o ./nytprof -f ./nytprof.out.*; rm ./nytprof.out.*"
alias ytcp="cover -delete -silent; rm ./nytprof.out.*; yath test --cover --nytprof; cover -silent; nytprofhtml -d -o ./nytprof -f ./nytprof.out.*; rm ./nytprof.out.*"

alias t2s="perl -p -i -e 's/\t/    /g'"
alias pb="perlbrew"
alias d="dest"

alias r="reply"
alias repl="reply"

function cpanf {
    if [ "$1" == '-l' ]
    then
        \grep "^\s*feature '.*sub" ~/.conf/cpanfile | perl -F"/'([^']+)'/" -ae "printf qq{%-10s %s\n}, @F[1,3]"
    elif [ "$1" == '-f' ]
    then
        cat ~/.conf/cpanfile
    elif [ "$1" == '-i' ]
    then
        for feature in $*
        do
            if [ "$feature" == '-i' ]
            then
                continue
            fi
            cpanm --installdeps ~/.conf --with-feature=$feature
        done
    elif [ "$1" == '-a' ]
    then
        for feature in $( cpanf -l | cut -d' ' -f1 )
        do
            cpanf -i $feature
        done
    else
        cat << EOF

Usage: cpanf [switch] [arguments]

    -l    list cpanfile feature names
    -f    cpanfile contents in full
    -i    install one or more features ("cpanf -i dev test cover")
    -a    install all features
    -h    help (this)

EOF
    fi
}

function pb_lib_cp {
    perl -MExtUtils::Installed -E 'say for ExtUtils::Installed->new->modules' > /tmp/pblibcp_$$

    perlbrew lib create $1
    perlbrew use @$1

    cat /tmp/pblibcp_$$ | cpanm --interactive
    rm /tmp/pblibcp_$$
}

function pb_vers_inst {
    for version in $(
        perlbrew available | grep perl | grep -v '^i' | grep -v 'cperl' | egrep -v '0\s*$' | \
        xargs perl -e '
            for (@ARGV) {
                /(perl\-\d+\.\d+)\.(\d+)/;
                $ver{$1} = $2 if ( not $ver{$1} or $ver{$1} < $2 );
            }
            print join( "\n", reverse sort map { $_ . q(.) . $ver{$_} } keys %ver ), "\n";
        '
    )
    do
        sudo su -l root bash -c "perlbrew install -n $version"
    done
}

function public_perl_dev_stuff {
    cd
    mcd github
    github_clone
    cpanf -a
    github_cpan
    pb_vers_inst
}
