#!/usr/bin/env bash

alias j='jobs -l'
alias ps="ps auxf"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias procs="ps -ef | tr -s ' ' | cut -d ' ' -f8 | grep -v '^\[' | grep -v CMD | sort | uniq -c | sort -nr"

function _my_ps {
    ps $@ -u $USER -o pid,%cpu,%mem,bsdtime,command
}

function pp {
    _my_ps f | awk '!/awk/ && $0~var' var=${1:-".*"}
}

# kill by process name
function killps {
    local pid pname sig="-TERM"
    if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]
    then
        echo "Usage: killps [-SIGNAL] pattern"
        return;
    fi
    if [ $# = 2 ]
    then
        sig=$1
    fi
    for pid in $( _my_ps | awk '!/awk/ && $0~pat { print $1 }' pat=${!#} )
    do
        pname=$( _my_ps | awk '$1~var { print $5 }' var=$pid )
        if ask "Kill process $pid <$pname> with signal $sig?"
        then
            kill $sig $pid
        fi
    done
}
